-libraryjars C:\WTK2.5.2_01\lib\mmapi.jar;C:\WTK2.5.2_01\lib\midpapi20.jar;C:\WTK2.5.2_01\lib\cldcapi11.jar
-injars C:\Documents and Settings\Admin\j2mewtk\2.5.2\apps\Classic Tetris\bin\Classic Tetris.jar
-outjar C:\DOCUME~1\Admin\LOCALS~1\Temp\Classic Tetris.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
-dontusemixedcaseclassnames
